#!/usr/bin/env bash

# Code to download raw data was generated by https://sra-explorer.info and further adapted
curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR139/083/SRR13989883/SRR13989883_1.fastq.gz -o Control_Hypoxia_1_R1.fastq.gz
curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR139/083/SRR13989883/SRR13989883_2.fastq.gz -o Control_Hypoxia_1_R2.fastq.gz
curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR139/084/SRR13989884/SRR13989884_1.fastq.gz -o Control_Hypoxia_2_R1.fastq.gz
curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR139/084/SRR13989884/SRR13989884_2.fastq.gz -o Control_Hypoxia_2_R2.fastq.gz
curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR139/081/SRR13989881/SRR13989881_1.fastq.gz -o Control_1_R1.fastq.gz
curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR139/081/SRR13989881/SRR13989881_2.fastq.gz -o Control_1_R2.fastq.gz
curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR139/082/SRR13989882/SRR13989882_1.fastq.gz -o Control_2_R1.fastq.gz
curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR139/082/SRR13989882/SRR13989882_2.fastq.gz -o Control_2_R2.fastq.gz

for FILE in $(ls *.fastq.gz); do
    pigz -c $FILE | head -4000000 | pigz > downsampled_$FILE
    rm $FILE
    mv downsampled_$FILE $FILE
done
